# To run the ingestion script using the Docker image:
# docker run --env-file .env pg-to-snowflake

services:
  postgres:
    image: "postgres:11"
    container_name: "postgres11"
    environment:
      POSTGRES_USER: 'neondb_owner'
      POSTGRES_PASSWORD: 'npg_rTE81kCXxLGl'
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
